// ═══════════════════════════════════════════
// levels.js — Puzzle Level Definitions
// ═══════════════════════════════════════════

export const LEVELS = [
  {
    id: 1,
    name: 'Overload Prevention',
    rows: 5,
    cols: 5,
    targetVoltage: 2,
    fixedTiles: [
      { row: 4, col: 2, kind: 'source',   voltage: 7 },
      { row: 0, col: 2, kind: 'endnode' },
      { row: 3, col: 2, kind: 'modifier', value: -1, connections: [0, 2] },
      { row: 2, col: 2, kind: 'modifier', value: -2, connections: [1, 2, 3] },
      { row: 3, col: 1, kind: 'xblock' },
      { row: 3, col: 3, kind: 'xblock' },
      { row: 0, col: 0, kind: 'xblock' },
      { row: 0, col: 4, kind: 'xblock' },
    ],
    inventory: [
      { type: 'STRAIGHT_H',  count: 2, panel: 'left' },
      { type: 'CORNER_TR',   count: 6, panel: 'left' },
      { type: 'MOD_SUB_1_C', count: 2, panel: 'left' },
      { type: 'MOD_ADD_1',   count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_2',   count: 1, panel: 'left' }, // Decoy
    ],
  },
  {
    id: 2,
    name: 'Multiverse Relay',
    rows: 7,
    cols: 7,
    targetVoltage: 4,
    fixedTiles: [
      { row: 6, col: 3, kind: 'source', voltage: 10 },
      { row: 0, col: 1, kind: 'endnode' },
      { row: 0, col: 5, kind: 'endnode' },
      { row: 5, col: 3, kind: 'modifier', value: -2, connections: [1, 2, 3] },
      { row: 6, col: 2, kind: 'xblock' },
      { row: 6, col: 4, kind: 'xblock' },
      { row: 4, col: 2, kind: 'xblock' },
      { row: 4, col: 4, kind: 'xblock' },
      { row: 4, col: 3, kind: 'xblock' },
      { row: 3, col: 3, kind: 'xblock' },
      { row: 2, col: 3, kind: 'xblock' },
      { row: 1, col: 3, kind: 'xblock' },
      { row: 0, col: 3, kind: 'xblock' },
      // Scattered maze blocks
      { row: 6, col: 0, kind: 'xblock' },
      { row: 6, col: 1, kind: 'xblock' },
      { row: 6, col: 5, kind: 'xblock' },
      { row: 6, col: 6, kind: 'xblock' },
      { row: 5, col: 0, kind: 'xblock' },
      { row: 5, col: 6, kind: 'xblock' },
      { row: 4, col: 0, kind: 'xblock' },
      { row: 4, col: 6, kind: 'xblock' },
      { row: 3, col: 0, kind: 'xblock' },
      { row: 3, col: 6, kind: 'xblock' },
      { row: 2, col: 0, kind: 'xblock' },
      { row: 2, col: 1, kind: 'xblock' },
      { row: 2, col: 5, kind: 'xblock' },
      { row: 2, col: 6, kind: 'xblock' },
      { row: 1, col: 0, kind: 'xblock' },
      { row: 1, col: 6, kind: 'xblock' },
      { row: 0, col: 0, kind: 'xblock' },
      { row: 0, col: 6, kind: 'xblock' },
      { row: 0, col: 2, kind: 'xblock' },
      { row: 0, col: 4, kind: 'xblock' },
    ],
    inventory: [
      { type: 'STRAIGHT_H',  count: 6, panel: 'left' },
      { type: 'CORNER_TR',   count: 8, panel: 'left' },
      { type: 'MOD_SUB_3_C', count: 2, panel: 'left' },
      { type: 'MOD_ADD_1',   count: 2, panel: 'left' },
      { type: 'MOD_SUB_2_C', count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_ADD_1_C', count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_3',   count: 1, panel: 'left' }, // Decoy
    ],
  },
  {
    id: 3,
    name: 'Oscorp Grid Bypass',
    rows: 8,
    cols: 8,
    targetVoltage: 6,
    fixedTiles: [
      { row: 7, col: 4, kind: 'source', voltage: 12 },
      { row: 0, col: 2, kind: 'endnode' },
      { row: 0, col: 6, kind: 'endnode' },
      { row: 6, col: 4, kind: 'modifier', value: -2, connections: [1, 2, 3] },
      { row: 3, col: 1, kind: 'modifier', value: -5, connections: [0, 2] },
      // Winding Scattered Maze Blocks
      { row: 7, col: 0, kind: 'xblock' },
      { row: 7, col: 1, kind: 'xblock' },
      { row: 7, col: 2, kind: 'xblock' },
      { row: 7, col: 3, kind: 'xblock' },
      { row: 7, col: 5, kind: 'xblock' },
      { row: 7, col: 6, kind: 'xblock' },
      { row: 7, col: 7, kind: 'xblock' },
      { row: 6, col: 0, kind: 'xblock' },
      { row: 6, col: 1, kind: 'xblock' },
      { row: 6, col: 7, kind: 'xblock' },
      { row: 5, col: 1, kind: 'xblock' },
      { row: 5, col: 3, kind: 'xblock' },
      { row: 5, col: 4, kind: 'xblock' },
      { row: 5, col: 5, kind: 'xblock' },
      { row: 5, col: 7, kind: 'xblock' },
      { row: 4, col: 0, kind: 'xblock' },
      { row: 4, col: 4, kind: 'xblock' },
      { row: 4, col: 7, kind: 'xblock' },
      { row: 3, col: 0, kind: 'xblock' },
      { row: 3, col: 4, kind: 'xblock' },
      { row: 3, col: 7, kind: 'xblock' },
      { row: 2, col: 0, kind: 'xblock' },
      { row: 2, col: 3, kind: 'xblock' },
      { row: 2, col: 4, kind: 'xblock' },
      { row: 2, col: 5, kind: 'xblock' },
      { row: 2, col: 7, kind: 'xblock' },
      { row: 1, col: 0, kind: 'xblock' },
      { row: 1, col: 1, kind: 'xblock' },
      { row: 1, col: 3, kind: 'xblock' },
      { row: 1, col: 4, kind: 'xblock' },
      { row: 1, col: 5, kind: 'xblock' },
      { row: 1, col: 7, kind: 'xblock' },
      { row: 0, col: 0, kind: 'xblock' },
      { row: 0, col: 1, kind: 'xblock' },
      { row: 0, col: 3, kind: 'xblock' },
      { row: 0, col: 4, kind: 'xblock' },
      { row: 0, col: 5, kind: 'xblock' },
      { row: 0, col: 7, kind: 'xblock' },
    ],
    inventory: [
      { type: 'STRAIGHT_H',  count: 6, panel: 'left' },
      { type: 'CORNER_TR',   count: 8, panel: 'left' },
      { type: 'MOD_SUB_3_C', count: 2, panel: 'left' },
      { type: 'MOD_ADD_1',   count: 2, panel: 'left' },
      { type: 'MOD_SUB_2_C', count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_3',   count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_ADD_1_C', count: 1, panel: 'left' }, // Decoy
    ],
  },
  {
    id: 4,
    name: 'Symbiote Containment',
    rows: 9,
    cols: 9,
    targetVoltage: 5,
    fixedTiles: [
      { row: 8, col: 4, kind: 'source', voltage: 14 },
      { row: 0, col: 1, kind: 'endnode' },
      { row: 0, col: 4, kind: 'endnode' },
      { row: 0, col: 7, kind: 'endnode' },
      { row: 7, col: 4, kind: 'modifier', value: -3, connections: [0, 2] },
      { row: 3, col: 4, kind: 'modifier', value: -2, connections: [0, 2] },
      // Maze structure with decoy dead-ends
      { row: 8, col: 3, kind: 'xblock' },
      { row: 8, col: 5, kind: 'xblock' },
      { row: 7, col: 3, kind: 'xblock' },
      { row: 7, col: 5, kind: 'xblock' },
      { row: 5, col: 3, kind: 'xblock' },
      { row: 5, col: 5, kind: 'xblock' },
      { row: 4, col: 3, kind: 'xblock' },
      { row: 4, col: 5, kind: 'xblock' },
      { row: 3, col: 3, kind: 'xblock' },
      { row: 3, col: 5, kind: 'xblock' },
      { row: 2, col: 3, kind: 'xblock' },
      { row: 2, col: 5, kind: 'xblock' },
      { row: 1, col: 3, kind: 'xblock' },
      { row: 1, col: 5, kind: 'xblock' },
      { row: 0, col: 3, kind: 'xblock' },
      { row: 0, col: 5, kind: 'xblock' },
      { row: 5, col: 2, kind: 'xblock' },
      { row: 2, col: 2, kind: 'xblock' },
      { row: 1, col: 2, kind: 'xblock' },
      { row: 5, col: 6, kind: 'xblock' },
      { row: 2, col: 6, kind: 'xblock' },
      { row: 1, col: 6, kind: 'xblock' },
      // Extra scattered outer blocks
      { row: 8, col: 0, kind: 'xblock' },
      { row: 8, col: 1, kind: 'xblock' },
      { row: 8, col: 2, kind: 'xblock' },
      { row: 8, col: 6, kind: 'xblock' },
      { row: 8, col: 7, kind: 'xblock' },
      { row: 8, col: 8, kind: 'xblock' },
      { row: 7, col: 0, kind: 'xblock' },
      { row: 7, col: 8, kind: 'xblock' },
      { row: 6, col: 0, kind: 'xblock' },
      { row: 6, col: 8, kind: 'xblock' },
      { row: 5, col: 0, kind: 'xblock' },
      { row: 5, col: 8, kind: 'xblock' },
      { row: 4, col: 0, kind: 'xblock' },
      { row: 4, col: 8, kind: 'xblock' },
      { row: 3, col: 0, kind: 'xblock' },
      { row: 3, col: 8, kind: 'xblock' },
      { row: 2, col: 0, kind: 'xblock' },
      { row: 2, col: 8, kind: 'xblock' },
      { row: 1, col: 0, kind: 'xblock' },
      { row: 1, col: 8, kind: 'xblock' },
      { row: 0, col: 0, kind: 'xblock' },
      { row: 0, col: 8, kind: 'xblock' },
      { row: 0, col: 2, kind: 'xblock' },
      { row: 0, col: 6, kind: 'xblock' },
    ],
    inventory: [
      { type: 'CROSS',       count: 1, panel: 'left' },
      { type: 'STRAIGHT_H',  count: 14, panel: 'left' },
      { type: 'CORNER_TR',   count: 8, panel: 'left' },
      { type: 'MOD_SUB_2_C', count: 2, panel: 'left' },
      { type: 'MOD_ADD_1',   count: 2, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_3_C', count: 1, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_2',   count: 1, panel: 'left' }, // Decoy
    ],
  },
  {
    id: 5,
    name: 'Spider-Verse Core Overload',
    rows: 10,
    cols: 10,
    targetVoltage: 6,
    fixedTiles: [
      { row: 9, col: 0, kind: 'source', voltage: 20 },
      { row: 0, col: 0, kind: 'endnode' },
      { row: 0, col: 5, kind: 'endnode' },
      { row: 0, col: 9, kind: 'endnode' },
      { row: 9, col: 3, kind: 'modifier', value: -2, connections: [1, 3] },
      { row: 7, col: 1, kind: 'modifier', value: -3, connections: [0, 2] },
      { row: 7, col: 8, kind: 'modifier', value: -3, connections: [0, 2] },
      { row: 9, col: 6, kind: 'xblock' },
      { row: 9, col: 7, kind: 'xblock' },
      { row: 9, col: 8, kind: 'xblock' },
      { row: 9, col: 9, kind: 'xblock' },
      { row: 8, col: 0, kind: 'xblock' },
      { row: 8, col: 9, kind: 'xblock' },
      { row: 7, col: 0, kind: 'xblock' },
      { row: 7, col: 2, kind: 'xblock' },
      { row: 7, col: 3, kind: 'xblock' },
      { row: 7, col: 4, kind: 'xblock' },
      { row: 7, col: 5, kind: 'xblock' },
      { row: 7, col: 6, kind: 'xblock' },
      { row: 7, col: 7, kind: 'xblock' },
      { row: 7, col: 9, kind: 'xblock' },
      { row: 6, col: 6, kind: 'xblock' },
      { row: 6, col: 7, kind: 'xblock' },
      { row: 6, col: 9, kind: 'xblock' },
      { row: 5, col: 1, kind: 'xblock' },
      { row: 5, col: 2, kind: 'xblock' },
      { row: 5, col: 3, kind: 'xblock' },
      { row: 5, col: 4, kind: 'xblock' },
      { row: 5, col: 6, kind: 'xblock' },
      { row: 5, col: 7, kind: 'xblock' },
      { row: 5, col: 9, kind: 'xblock' },
      { row: 4, col: 1, kind: 'xblock' },
      { row: 4, col: 2, kind: 'xblock' },
      { row: 4, col: 3, kind: 'xblock' },
      { row: 4, col: 4, kind: 'xblock' },
      { row: 4, col: 6, kind: 'xblock' },
      { row: 4, col: 7, kind: 'xblock' },
      { row: 4, col: 9, kind: 'xblock' },
      { row: 3, col: 1, kind: 'xblock' },
      { row: 3, col: 2, kind: 'xblock' },
      { row: 3, col: 3, kind: 'xblock' },
      { row: 3, col: 4, kind: 'xblock' },
      { row: 3, col: 6, kind: 'xblock' },
      { row: 3, col: 7, kind: 'xblock' },
      { row: 2, col: 1, kind: 'xblock' },
      { row: 2, col: 2, kind: 'xblock' },
      { row: 2, col: 3, kind: 'xblock' },
      { row: 2, col: 4, kind: 'xblock' },
      { row: 2, col: 6, kind: 'xblock' },
      { row: 2, col: 7, kind: 'xblock' },
      { row: 2, col: 8, kind: 'xblock' },
      { row: 1, col: 1, kind: 'xblock' },
      { row: 1, col: 2, kind: 'xblock' },
      { row: 1, col: 3, kind: 'xblock' },
      { row: 1, col: 4, kind: 'xblock' },
      { row: 1, col: 6, kind: 'xblock' },
      { row: 1, col: 7, kind: 'xblock' },
      { row: 1, col: 8, kind: 'xblock' },
      { row: 0, col: 1, kind: 'xblock' },
      { row: 0, col: 2, kind: 'xblock' },
      { row: 0, col: 3, kind: 'xblock' },
      { row: 0, col: 4, kind: 'xblock' },
      { row: 0, col: 6, kind: 'xblock' },
      { row: 0, col: 7, kind: 'xblock' },
      { row: 0, col: 8, kind: 'xblock' },
    ],
    inventory: [
      { type: 'STRAIGHT_H',  count: 21, panel: 'left' },
      { type: 'CORNER_TR',   count: 6, panel: 'left' },
      { type: 'T_LRB',       count: 2, panel: 'left' },
      { type: 'MOD_SUB_3',   count: 2, panel: 'left' },
      { type: 'MOD_SUB_3_C', count: 1, panel: 'left' },
      { type: 'MOD_ADD_1',   count: 3, panel: 'left' },
      { type: 'MOD_SUB_2_C', count: 2, panel: 'left' }, // Decoy
      { type: 'MOD_ADD_1_C', count: 2, panel: 'left' }, // Decoy
      { type: 'MOD_SUB_1_C', count: 1, panel: 'left' }, // Decoy
    ],
  },
];
